### ISSUE TITLE
Require code owner on newly contributed integrations

### ISSUE THREAD

**Issue by frenck** [home-assistant/architecture#287] opened 2019-09-13 16:47 UTC
## Context

We get a lot of new integrations every release, which is really great!

Unfortunately, adding oneself as the code owner doesn't happen that often.

This has several drawbacks:

- Nobody "owns" the code from the start.
- Early bugs are less likely to be fixed.
- Our GitHub bot will not notify the contributor without a code owner.

A nice recent example:

Contribution: [Add vivotek camera component](https://github.com/home-assistant/home-assistant/pull/26071)
The issue raised during the beta period introducing this integration: <https://github.com/home-assistant/home-assistant/issues/26607>

(please note the above issue can still be fixed before the final release, however, I wanted to point out the code owner was missing from the initial contribution and, therefore, the issue raised during beta not assigned).

## Proposal

~~For the contribution of new integrations, a code owner is required and integrations without a code owner will no longer be accepted. Internal integrations are excepted from this rule.~~

For the contribution of new integrations, adding new functionality to an integration or doing significant refactoring of an integration; Adding oneself a code owner is required, integrations without it, will no longer be accepted. Internal integrations are excepted from this rule.

However, a contributor is allowed to remove itself as code owner after the stable release (e.g., due to lack of time to keep contributing to the project).

ℹ️**Proposal text changed based on feedback on this issue. Source: https://github.com/home-assistant/architecture/issues/287#issuecomment-531345316**

## Consequences

We are no longer accepting new integrations without a code owner. This may lead to fewer contributions, however, most likely better maintained as it is more likely the contributor is taking more responsibility for his contribution.

## Timeline

Based on the response to this proposal, I will open up a PR with an ADR on **Tuesday, 17 September 2019**.

**Comment by pvizeli** [comment] 2019-09-13 16:50
I full agree

**Comment by dmulcahey** [comment] 2019-09-13 16:59
I think this is a good idea as well.

**Comment by frenck** [comment] 2019-09-13 17:37
Just a thought, does this apply to integrations without a code owner, receiving a large contribution (like a refactor or rewrite)?

**Comment by Kane610** [comment] 2019-09-13 17:39
It should. I got shared code owner when fixing bonjour discovery

**Comment by frenck** [comment] 2019-09-13 18:11
@Kane610 Interesting, not considered that scenario.

However, both cases have an issue: The definition of a significant contribution to integration. This would be hard to quantify.

**Comment by dshokouhi** [comment] 2019-09-13 18:17
Maybe go by the amount of submissions? If a user is actively updating an integration?

**Comment by Adminiuga** [comment] 2019-09-13 18:29
you touch it you own it :)

**Comment by iantrich** [comment] 2019-09-13 18:31
that might discourage some ¯_(ツ)_/¯

**Comment by frenck** [comment] 2019-09-13 18:33
@Adminiuga That might scare some contributors that simply provide a bug fix. But there is something useful in there as well.

How about:

> For the contribution of new integrations, adding new functionality to an integration or doing significant refactoring to an integration; Adding oneself a code owner is required, integrations without it, will no longer be accepted. Internal integrations are excepted from this rule.

**Comment by arsaboo** [comment] 2019-09-13 18:54
I think, we should only force it for new integrations or significant refactoring (even this can be avoided). No point discouraging feature additions.

**Comment by iantrich** [comment] 2019-09-13 18:55
I would say no point discouraging bug fixes. But adding features is significant and should be linked to someone IMO

**Comment by dshokouhi** [comment] 2019-09-13 18:56
Thats why I suggested going by the number of submissions for the integration because that shows intention to make it better.

**Comment by frenck** [comment] 2019-09-13 18:57
@dshokouhi You can measure the impact of code by number of contributions....

**Comment by Adminiuga** [comment] 2019-09-13 19:00
You may want to account the number of contribution into underlying lib as well.

**Comment by frenck** [comment] 2019-09-13 19:00
@Adminiuga That is impossible to keep track off

**Comment by iantrich** [comment] 2019-09-13 19:01
Yeah, I don't think is going to be something that can be automated. A reviewer will need to make a judgement call. I don't want to be added as a codeowner because I fixed typos or something.

**Comment by frenck** [comment] 2019-09-13 19:05
@iantrich Parts of it can be automated. We already have labels for new integrations or new platforms, so those can be used for a code owner check I guess.

**Comment by dgomes** [comment] 2019-09-13 19:42
I think people reviewing the contribution are perfectly capable of judging if the contribution is major/minor and requires code ownership assignment. So it just becomes part of the review process.

**Comment by cgarwood** [comment] 2019-09-13 23:34
Only thing I might change is if an integration has an active codeowner, and someone else just submits a PR adding a feature they shouldn't necessarily have to add themselves as a codeowner. But for integrations with no codeowner or unresponsive codeowners, then we should seek to update the list with people who are active.

**Comment by frenck** [comment] 2019-09-14 11:13
I personally think having multiple code owners (even when we already have a active code owner) helps.

For example, it would instantly get code owners to be able to review each other’s work (since they have context on the subject), which is a major plus.

Secondly, even currently active contributors can drop off the grid, having another active one on an integration adds a fallback.

**Comment by balloob** [comment] 2019-09-14 13:38
Agree with all of this.

Two code owners is heaven. Take ZHA, two people with high expertise are fixing things and reviewing each other work. Fast turnaround time.

**Comment by ties** [comment] 2019-09-14 18:25
> I think people reviewing the contribution are perfectly capable of judging if the contribution is major/minor and requires code ownership assignment. So it just becomes part of the review process.

Could even explicitly ask whether a contributor wants to become a codeowner when adding a feature.

The only issue there is that each codeowner may only be responsibe for part of the code. For example, just the camera platform for some weather platforms.

**Comment by pvizeli** [comment] 2019-09-15 19:38
@ties if a component have allready a code owner, they can self manage how many code owner they want have. It is important that every core component have a responsible person they review and help to test the component.

**Comment by amelchio** [comment] 2019-09-15 20:05
I agree with @ties, we should not make an ADR about this.

It’s fine if reviewers encourage contributors to become code owners. However, that should not be an automatic process. It should be a judgement call based on things like size, quality and attitude in the contribution.

That way, being a codeowner is an honor, not a chore.

If you want something in writing, I think a single point in one of the checklists could be enough: _If you are making significant changes to an integration, please consider adding yourself as a codeowner to be notified of any regressions._

**Comment by frenck** [comment] 2019-09-16 05:17
“The honor”? This is not about honors, but about taking responsibility.

**Comment by amelchio** [comment] 2019-09-16 06:29
Responsibility is indeed something that one _takes_. You can only encourage, you cannot force it upon people, especially volunteers. So rather than a penalty, it's better to make it a prize that people accept.

**Comment by pvizeli** [comment] 2019-09-16 07:56
@amelchio and such integration should not be in core, they can handle as custom integrations. We speak about that every new integration needs a code owner. Other is point of view of reviewer.

**Comment by Jc2k** [comment] 2019-09-16 08:46
I agree 100% that if you submit a new integration you should be prepared to be a codeowner and support it. Getting something into the main repo means it’s valuable to more than just you. You need to come at it ready to have that responsibility.

I wanted to throw in that when I was asked to be a codeowner for an existing integration it was an honor and it was a reward. There was no pomp and ceremony, it was mundane and business as  usual thing. But I felt like I had earned some level of trust with the core HA team. It validated me and it validated my efforts. I am thankful for it.

**Comment by ties** [comment] 2019-09-16 09:52
> “The honor”? This is not about honors, but about taking responsibility.

It's about honor. Honor in maintaining something. You can setup the process, but the owner of the component needs to actually interested and involved for that to work. This is volunteer work [in free time].

**Comment by frenck** [comment] 2019-09-17 10:00
100% agreed @ties, hence proposing the requirement to filter those people from the people that don't feel that "honor".

**Comment by amelchio** [comment] 2019-09-17 18:54
The proposal does not do that. It is just red tape.

**Comment by ties** [comment] 2019-09-17 19:44
> The proposal does not do that. It is just red tape.

Right now it is. We have seen very narrow readings of ADR's (e.g. the web scraping ADR) so I'm firmly against specific wording in an ADR.

An ADR could describe the issue (integrations with errors but no active maintainer) and the proposed solution (attempting to get as many integrations active owners as possible, including core, since exceptions are the beginning of a slippery slope).

It is an honour system. We have all dealt with co-workers who don't feel ownership of code they wrote that is under-documented and has issues. In this case, contributors are not getting paid. Having multiple owners is ideal when doing code reviews; they would understand the implementation better.

I would propose to add questions for the following scenarios in the pull request form. Proposed wording:
  * This is a newly supported device and I would like to support this code in the future.
  * This contributes new functionality to a device and I would like to support this moving forward.
  * This pull request fixes a bug, but I would like to support this component in the future.

**Comment by frenck** [comment] 2019-09-17 19:49
> The proposal does not do that. It is just red tape.

yes.

> - This is a newly supported device and I would like to support this code in the future.
> - This contributes new functionality to a device and I would like to support this moving forward.
> - This pull request fixes a bug, but I would like to support this component in the future.

Avoiding new contributions to the core by a contributor who answer "NO" to one of these, is one of the goals. 🤷‍♂

**Comment by ties** [comment] 2019-09-17 20:01
> Avoiding new contributions to the core by a contributor who answer "NO" to one of these, is one of the goals. 🤷‍♂

The situation is a communication problem. To be addressed at the point in time where someone answers no instead of with red tape. The _worst_ situation is when someone answers yes because of the red tape without the commitment needed to actually do so.

To set a good example it may even be good to remove the exception for internal integrations. This would make it more explicit that they _already_are_ "maintained by the core team".

> 
> > * This pull request fixes a bug, but I would like to support this component in the future.
> 
> That is not covered by any of this ADR, and left out of scope for the code ownership.

The goal is to have more supported components and improve the situation. But indeed, if you narrowly read it this is out of scope.

**Comment by frenck** [comment] 2019-09-17 21:53
Thanks all for contributing to the proposal, I'm happy with all the responses and insights you guys gave.

I'm writing up a PR with the ADR reflecting the core of the proposal and will extend the text to be a little more forgiving and try to include add as much as the feedback given here. I'll post a link to the PR in this issue, so you guys can give a final check/go/no-go.

**Comment by amelchio** [comment] 2019-09-18 15:58
> The situation is a communication problem.

I think you are right about that. For example, nobody has defined what code owner even means. Yet, we are discussing if people should be one and whether it’s an honor or not.

AFAIK, a code owner in the Home Assistant organization has no privileges and no duties per se so it is literally just a notification list.

Also, speaking of communication problems, we have a rather poor track record with ADR so far. Almost all of them are ambiguous and have been a cause of renewed discussion. A lot of effort goes into figuring out what the current policy is or should be.

I maintain that we should not spend those resources on petty details such as notification lists.

**Comment by frenck** [comment] 2019-09-18 19:25
> I maintain that we should not spend those resources on petty details such as notification lists.

I absolutely and strongly do not agree on that. Notifications to code owners have been really effective. Turnaround time on those issues and PR's are higher. A lot of contributors do not constantly check if there is something in the ~800-1000 issues or the 100+ PR's for them based on keywords.

**Comment by Jc2k** [comment] 2019-09-18 20:12
The codeowner notifications are essential to my workflow, so I am with @frenck here.

**Comment by frenck** [comment] 2019-09-18 20:51
Following up on the discussion we had in this architectural issue, I've opened up PR #290 to add `ADR 0008: Code owners`.

**Comment by amelchio** [comment] 2019-09-19 15:08
I never said that some people should be denied notifications.

**Closed** 2019-09-20 11:37 UTC
