### ISSUE TITLE
Release cycle

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/architecture#192] opened 2019-04-11 07:43 UTC
I want to change the release cycle to 3 Weeks terms.

## Idea
```
Prod Release x
[ 2 Week ]
Beta Release yb
[ 1 Week ]
Prod Release y
```

## Why?

Home Assistant Ecosystem is so big now with all the project and also there release circle. A Home Assistant Release is also not a small work because another maintainer like me need to test it on Docker and other growing mechanics.

The Release of Home Assistant is also not a small work and need every time a lot of efforts. We lost so many times, and it's so stressed with this weekly releasing of Prod/Beta.

I can take a lot more productivity if we have 1 Week more between Prod and Beta. At last, I see a lot of hurry merges and a lot of bugfixes after there. I also think a Week more help to make things more stable.

Reason for a week more between stable/beta is that more time to fix the beta is not needed because the developer doesn't do that as the initial idea was, but it's okay like it is now. A week more to fix new feature on dev is more used/common by the developers.

**Comment by robbiet480** [comment] 2019-04-11 08:52
Once all components go external, could we not actually _speed up_ to our previous cadence of one release a week? There would be a lot less merges and hopefully breaking changes in the base API.

If that assessment is incorrect, then this proposal seems fine.

**Comment by pvizeli** [comment] 2019-04-11 09:36
If integrations are breaking out, we should slow done to one release on month because we need to give the developers time to follow all change and integrate it. Otherwise, they give up after three months if there need to follow every week's Home Assistant changelogs. But that is not the topic now.

Review, writing a blog post, preparing releases, test integrations, and many other steps need time. I think one week more in the process help to improve the quality and minimize the overhead on release working and all following jobs. Give also time to people to help tests components and fix bugs.

More time between new feature make also the user to use the beta more frequently.

I say only, like it is now, the quality going away. And a lot user doesn't update his Home Assistant device too often because after 3 months there are so many changes and release notes to read that they don't do it anymore and run into issues.

**Comment by rohankapoorcom** [comment] 2019-04-11 15:07
I agree, I feel like in the last few releases in particular, we've been struggling to get things through the PR process in time to get into the release which puts strain on everyone involved.

**Comment by ludeeus** [comment] 2019-04-11 16:24
I do agree on a longer cycle.
And to build on @rohankapoorcom 's comment, if the "dev" period is extended then the "beta/test" period also need to be extended, without doing that it could result in bigger (and potentially more unstable due to a shorter beta/test period) releases.

**Comment by DubhAd** [comment] 2019-04-11 17:26
I'd be quite happy to see a longer/slower release cycle, assuming that the longer period includes a longer test window, and ideally either a test plan or at least a list of things that have been changed and so need testing.

**Comment by balloob** [comment] 2019-04-11 17:56
So the only challenge with an extended beta cycle is that it sometimes is difficult to cherry pick fixes to the beta from dev, if dev has ventured too far away.

Would it help if we just start fully overlapping them? Each time we do a new release, we do a new beta release too? Some thoughts:

 - longer time to fix beta stuff
 - that time is shared with adding new features
 - release day becomes a bit heavier as we have to publish both releases. We give priority to normal release. Maybe do beta on next day?

```
|    Beta 0.92     |    Beta 0.93     |
|   Release 0.91   |   Release 0.92   |
```

**Comment by olbjan** [comment] 2019-04-11 18:21
Would it be possible to add a list of things to test / areas touched to beta release notes? Having that pointer would help get input from people like me who can't help by doing dev but are able to test and look for regressions.

**Comment by arsaboo** [comment] 2019-04-11 19:01
@olbjan The release PR typically has everything linked. This information is also available on https://rc--home-assistant-docs.netlify.com/

**Comment by balloob** [comment] 2019-04-11 19:58
Maybe we should re-org release notes by integration, and then generate a 2nd list, with checkboxes so that people can validate that it works.

**Comment by dgomes** [comment] 2019-04-11 20:03
Here is an idea: 

- Have an integration change log in the manifest file

This way we could warn in advance a **personalized** change log

**Comment by ljmerza** [comment] 2019-04-15 17:38
I also think it's important to not add features/changes during beta. It should only be for bug fixes.

**Comment by balloob** [comment] 2019-04-15 17:54
@ljmerza that is already the case.

**Comment by ljmerza** [comment] 2019-04-15 18:02
someone removed `hui-error-entity-row` 2 days before release on 0.88. Looking at the last beta week with a release of April 3rd:

April 3rd::
* Require static-check success first for rest of workflow
* Add mobile_app notify platform
* Hass.io discovery flow deconz


April 2nd:
* Support GET params for websocket ingress path
* Update face_recognition to 1.2.3

March 31st:
* Add stream to the default config
* Update ONVIF component to SUPPORT_STREAM
* Update Amcrest component to SUPPORT_STREAM
* Google assistant: add blinds trait for covers 

March 29th:
* Add support for streaming to ffmpeg

The list goes on. These are new features being added literally the day before release.

**Comment by cgtobi** [comment] 2019-04-15 18:26
> * Require static-check success first for rest of workflow

This is related to the recent CI switch and is not an actual feature but a central part of the development cycle. 

> * Add mobile_app notify platform

This is (as far as I know) only used in the "still in beta" iOS companion app and should not affect other users.

And pretty much all other features listed are from one or maybe two dev cycles. As Paulus wrote it usually is the case and *maybe* some features have been rushed in one of the latest releases. But those integrations weren't really causing much trouble as far as I can tell from the issue tracker, do they?

**Comment by awarecan** [comment] 2019-04-16 01:44
That is partially true. Because we don't have rc branch for frontend, @balloob usually pay more attention to frontend project after beta cut, so you will find more frontend feature came in during the beta. Backend usually won't, unless for some important feature we want to bring in, and even so, they won't come in just one or two days before release.

**Comment by MartinHjelmare** [comment] 2019-04-16 07:43
It has happened on multiple occasions that "very cool" big features were added a couple of days before release. I think we should be more strict in following the rule we seem to agree that we have.

If you want an example, I remember the owntracks config entry support.

**Comment by awarecan** [comment] 2019-04-16 07:59
OwnTracks Config Entry
https://github.com/home-assistant/home-assistant/pull/18759

**Comment by frenck** [comment] 2019-04-17 08:45
I gave myself a couple of thoughts about this, before actually responding here.

There are many pros & cons for either of the suggestions. Extending the time between releases can be done on two places:

1) **Extend time between dev & beta**: Releases contain more changes, the beta period still unchanged. Risks of issues become harder and the stress in the beta period becomes higher.
2) **Extend time between beta & release**: More time to stabilize the release, but diverging from the dev branches might introduce new pains.

I guess this is the main drive behind the release fast & often concept a lot of dev teams use now a day, but I realize that is not an option for this project (depending on external contributors) and would definitely not be bearable by @balloob & @pvizeli.

Whatever we choose to do, IMHO extending the release cycle is at this point mainly for reducing stress from @pvizeli & @balloob, who are currently managing the releases. And releasing them from this "burden" will give them more time to work on the project ❤️

@balloob suggests doing a release & beta cut-off at the same time (in https://github.com/home-assistant/architecture/issues/192#issuecomment-482226578). This sounds ideal at first glance since it will close the gap a little between point 1 & 2 I've laid out earlier.

From a user perspective there are a couple of things that the community asks for (my interpretation):
- A) Stable releases
- B) New features quickly
- C) Fewer breaking changes

Breaking changes is a hot subject of discussion and frustration in the community. We all have our opinions on it and from a developer point of view, I agree on many of those are needed in order to move the project forward. That being said: The user hates them! Which I totally understand.

From a developer point of view, breaking changes at this point are not always avoidable. But from the user perspective, they feel like we are breaking their systems every 2 weeks right now. Extending the release period will most certainly help with this as well.

We see a lot of users not doing their upgrades, just because of the points mentioned earlier. Effectively making the effort we do for all those releases useless to that group of users as well.

**So my suggestion, based on the above is the following, little bold one: **

Introduce a **monthly** release cycle.

- Combine beta cut-off and release at the same date, as suggested by @balloob.
- Extend the release cycle and accept the risk of branches diverting and quite possibly the need for backporting patches from time to time.
- From a user experience point of view, less breaking changes: 12 a year instead of 24 (this is of course just a mental experience).
- More time to stabilize a release.
- Gives more time to contributors to help stabilize and more comfortable to fit in the "free spare time" they donate.
- Expecting more people to jump into the beta because of the longer time for the new feature to arrive, resulting in more widely tested features/releases.
- Easy to follow and remember (e.g., release on every first Monday of the month).
- Adds relief for @balloob & @pvizeli.

The main downside for the user and the price to pay: New features, less quick.

**Comment by pvizeli** [comment] 2019-04-17 09:32
Yeah, the monthly release cycle better for all and that what I would be going to have at the end.

I see now with the delay of 0.92 from 0.91 (a week like I say on initial post) is a lot more relaxed and allow to do a lot more and stable code changes without hurry up in last seconds.

@ljmerza 
Most of them are bugfix from things that didn't work. Like bumping the face detection library. The old didn't work anymore since 0.90
Next, are all beta feature they are not officially released and need moving to forward like Ingress/mobile integration.

**Comment by allanpersson** [comment] 2019-04-18 17:13
I like the idea of a fixed day for releases @frenck is suggesting. 
My point of view on the day is monday is a bad day for breaking changes for most people, friday fx. would be better, because of a full weekend ahead to fix breaking changes...

**Comment by arsaboo** [comment] 2019-04-18 17:15
@allanpersson You are assuming that devs are free on weekends to work on HA fixes :wink:

**Comment by allanpersson** [comment] 2019-04-18 17:18
@arsaboo i assume with monthly releases there will be no (less :P ) fixes, and users will have less (12) breaking changes, and with release to a weekend time to get them fixed, and less frustration for the users 💃

**Comment by olbjan** [comment] 2019-04-18 17:20
I would assume that with monthly releases the number of breaking changes per release would increase considerably, just because of more churn. At least for a while. Not that that is necessarily a bad thing at this point.

**Comment by awarecan** [comment] 2019-04-18 18:34
Wednesday release is a good choice so far.

**Comment by andrewsayre** [comment] 2019-04-22 00:45
I think it's important to keep in mind "time to feedback" is one of the most important metrics to a product.  The lower the time to ship new features, the better a product can meet user needs and respond to changes in the market.  In my experience, the perceived benefits of slowing down, rarely, if ever, overcome the cost of lost agility.
- I think most of the reasons to extend the cycle articulated in this issue are solved by stronger adherence to our guidelines, better engineering practices (to avoid or gracefully handle breaking changes), and better automation of the release.  Extending the release cycle doesn't make these issues better, it magnifies them.
- Considering @frenck's proposal, that would mean a 4-8 week lead time _after_ getting through our lengthy PR process.  It would be typical to have a 3 month "time to feedback" for new features, which is way too long.
- While extending beta will pull in more testers, I do not think it will be significant nor representative of the general user population.  Primary feedback _will still come_ when features actually ship.  For example, in developing the SmartThings integration, nearly all (90%+) bugs and feature requests came from releases and were often linear (i.e. after adding X and seeing how it worked, add Y too).

**I propose we table this issue (do not change our current release cycle) and instead focus on #202 and improving our developer guidelines and enforcing better engineering practices.  I think that would serve our user's better.**

**Comment by BradleyFord** [comment] 2019-04-22 01:50
Having a long window before release will also encourage more active users to move to beta to get the new features faster... Resulting in better testing of the release.

**Comment by andrewsayre** [comment] 2019-04-22 14:37
We should ask our users what they want (via a survey, poll, etc...).  How frequently do they want releases, would they become beta users to get new features faster, what level of support would be expected, etc...  Then we can make an objective data-driven decision.

@BradleyFord That comment has already been articulated in this issue and I responded that in the third bullet above.  Additionally, I think suggesting users become beta users just to get new features drives the wrong behavior.  Are we really going to get more testers? Or are we going to get people using it in PROD because we aren't meeting their needs (speed to market) and expecting the same level of support, having the same frustration about breaking changes (which is more prevalent in beta).

**Comment by Kane610** [comment] 2019-04-22 14:45
I'm with @andrewsayre on this. Apart from speed we also need to start measuring usage to evolve hass as a product.

https://janbosch.com/blog/index.php/2017/01/08/speed-data-and-ecosystems/

**Comment by pvizeli** [comment] 2019-04-22 15:18
@andrewsayre @Kane610 the problem is, currently user paid us to create release because a lot of our time is now with maintaining and coordinate release every week. I would be preferable to be paid to create new stuff, or fix exists bug.

**Comment by MarsWarrior** [comment] 2019-04-22 15:58
Although I would welcome a longer release cycle, I also doubt if the release cycle is the problem with hass.

**Situation:**
I maintain about 5 hass installations. All with different integrations and sensors. It almost has become a daily job to 'investigate' and 'fix' problems, which is a bad thing from my point of view as I won't be the only user experiencing this problem.

All installations use docker.

**My current problems with 0.91.x:**

- Utility sensor simply not working, my server consumes 124866.39 kWh yearly according to hass. And NO, I don't own a complete serverpark for Google
- Z-Wave constantly stops working since the end of March. I have to reboot hass to get things working again. This used to work for 6 years on OpenHab and worked **_flawlessly_** for 3 months on hass.
![Domiduca Power fails Zwave](https://user-images.githubusercontent.com/1220775/56507536-e6156a00-6521-11e9-8a9a-a56c8e04ba5a.png)
- Rebooting hass doesn't work always anymore. I have to go to Portainer to reboot the container
- Http related problems, so luftdaten fails often, esphome fails often and the mmi fails often
- Tradfri is causing problems: can't control lights, or lights go on, but can't be controlled anymore. Only a reboot of hass fixes things temporarily. 
- This issue, [(zigbee2mqtt #1461)](https://github.com/Koenkk/zigbee2mqtt/issues/1461) which is also an hass issue [#23298](https://github.com/home-assistant/home-assistant/issues/23298) actually shows what I mean: things just stop working from release to release
- The otgw component has started to give a lot of errors in the log like "Command PR failed with SC: 14:16/1, retrying..." or "Unknown message in command queue".

**And what keeps working?**
I moved several integrations to MQTT because of previous problems with hass versions breaking unexpectedly. **_These integrations just keep on working for the past 9 months_**, although they get regular updates too:

- Zigbee2mqtt for all zigbee related sensors and devices
- OTGW over mqtt to control my boiler
- Tasmota for all ESPxx devices
- Several other custom made devices

**Every new release fixes bugs, and introduces new ones**
I think that #202 will help a lot with the instability I'm experiencing. Currently if I update to get a bug fixed, I sometimes get new bugs for free, which leaves me with problems: rolling back gives me the old bugs, and rolling forward new bugs.

I'm currently looking in replacing z-wave integration with zwave to mqtt to get zwave working again.

**Put some kind of moratorium on the integration changes**
With the aid of #202 I think a moratorium on changes will be feasible: after testing an integration, fix it's version ('stable') and allow bug fixing only. No refactoring or other breaking stuff. Move all new development to the 'dev' or 'edge' channel. Edge for instance gets pushed to stable after 3 months.

Users can opt for the stable, edge or dev channels for their integrations, or set them to manual, ie fixed to a specific channel and/or version. This is exactly what I'm doing with all the mqtt integrations!

I know - as an IT project manager - that the above works 💯 

**Three channels with different release cycles?**
Well, as I said in my opening, I don't think changing the current release cycle will help if the main problem - instability by constant changes - is not addressed. My proposal thus would be using multiple release channels:

- users who want test beta's, help in development and fast problem fixing will use the dev channel
- users who want the newest features (just as now) AND are willing to experience problems will use edge channel
- users who just want hass to work will use the stable channel, and occasionally one of the other channels for added functionality or bug fixing.

**Comment by dgomes** [comment] 2019-04-22 20:56
Creating an edge and a stable channel might cause extra burden in integration developers that will need extra effort to play catchup with dev (lagging behind for a month might bring to many changes)

But conceptually I'm in favour of creating LTS releases that will ONLY get bug fixes for an extended period (lets say 1 month)

PS: @MarsWarrior open an issue about utility_meter, I would like to assist you on that

**Comment by awarecan** [comment] 2019-04-22 21:37
LTS is a serious commitment. A little off-topic, how many user are willing to spend, let us say, 20 dollars to subscribe a LTS build of HA?

**Comment by fabaff** [comment] 2019-04-24 11:48
I can remember a time when I spent pretty much the whole Saturday preparing the releases. Creating a new release is a boring tasks and doing it every other week is not a real pleasure and there is not much glory.

> More time between new feature make also the user to use the beta more frequently.

As already mentioned, shipping a new release is the only way to get feedback as the "user" audience is bigger than the one that is using "betas". But it will definitely not make users to "beta-testers".

- Developers don't run "betas", they run "dev"
- Users don't run "betas", they run "stable" releases
- Testers should run "betas" but there is no established and visible "Tester community" in our ecosystem 

Users will in most cases just wait till the new feature is in stable.

> @andrewsayre @Kane610 the problem is, currently user paid us to create release because a lot of our time is now with maintaining and coordinate release every week. I would be preferable to be paid to create new stuff, or fix exists bug.

For me this looks more like a Nabu Casa issue and not a Home Assistant one. Sure, there is a strong interconnection but users are not paying for releases they are paying for a feature that makes their life easier.

Most Open Source projects are having this kind of discussions. Can't really remember how many times this came up in the last 15 years in Fedora community and other projects. For some the release cycle is too short, for others too long, others want LTS releases and so on and on. We can't please everyone.

Going from a two week to a three week release cycle didn't solve the issue we wanted to solve, IMHO. A four week release cycle will simply postpone the work.

The add-ons and part of the documentation are already decoupled from the Home Assistant release cycle. Decoupling others things like Hass.io perhaps could free up/allow to shift resources as there could be some time between the releases. In case of Hass.io the users would get a more stable system as the bugfix releases are included and there is no need to build/test it for every bugfix releases. We are saying that the target audience for Hass.io are regular users or newbies. Thus those people would profit from an independent release cycle and often don't care if the release is not in sync with Home Assistant itself. They don't read the release notes but simply click the button to update.

Of course, this would need some more thinking and perhaps a process to get the best result.

**Comment by MarsWarrior** [comment] 2019-04-24 13:05
> Creating an edge and a stable channel might cause extra burden in integration developers that will need extra effort to play catchup with dev (lagging behind for a month might bring to many changes)

The idea of multiple channels should NOT create extra burden on the integration developers.
The idea is based on the implementation of #202, which should bring the same things as MQTT for the IoT world and all the existing hass MQTT integrations: stability and decoupling.

Hass has already shown that its MQTT integration, including autodiscovery, is a great solution.

In my view, the channels should  / can work as follows:

- An integration in the Edge channel is say updated to version 2.1 and gets subsequent bugfixes in 2.1.1, 2.1.2, 2.1.3 and 2.1.4
- Then after for example 3 months this version 2.1.4 is released in the stable channel. These users won't see the bugs between 2.1 and 2.1.4. And because of #202 there should be no need for extra integration testing as the interface is unchanged
- If there is an interface change in the core, this is handled using the manifest as proposed in #202. Meaning the 2.1.4 version might need an update of the core first. Nothing gets broken though!

So the stable channel is just a delayed/bug-fixed edge channel. There is no back-porting or cherry picking and thus extra/new integrations issues and testing required. No LTS efforts of some kind.

**Less bugs, less issues, less questions on the forums...**
If I look back at this year only, I see hass hovering around 1000 open issues. Some releases created much more issues than it solved. Every issue takes time from a developer to find the problem and fix it.

Every issue also annoys one or more users, some more of course than others. This results in more questions in the release blog / forums.  What if this time could be invested in quality releases?? What if the issue list (for bugs, not features or new integrations) would go down all the to way to 100?

**Users can upgrade in confidence**
The proposal won't be the silver bullet for everyone, but if it builds a strong user confidence in hass because users can simply upgrade hass or an integration to the latest release withoug breaking basic functionality like lights and enjoy new functionality, I guess everybody, from developer to tester to end user will be very happy.

> PS: @MarsWarrior open an issue about utility_meter, I would like to assist you on that

I will do that. I have some graphs showing that hass sometimes simply double the previous value, instead of adding an increment. I hope to find some examples in Grafana, as currently z-wave has failed again, so no power consumption updates available today...

**Comment by balloob** [comment] 2019-04-24 18:23
This discussion got completely derailed and the initial point is no longer discussed: Pascal and I are doing the grunt work of releases and with the current release cycle we hardly have any time to do anything else.

**Comment by rohankapoorcom** [comment] 2019-04-24 18:26
Can we distribute and/or automate more of the workload to reduce the burden on you and Pascal?

**Comment by SeanPM5** [comment] 2019-04-24 21:08
I think that a monthly release cycle would be significantly worse in terms of breaking changes because:

1) Combining two bi-weekly releases into one monthly update means at least **twice as many breaking changes per update**. 
2) Contributors would have additional time to make larger more ambitious changes resulting in longer code review times and most likely **even more breaking changes**.
3) The awesome contributors adding new features will constantly have their work overshadowed and drowned out by all the "how do I fix X and Y breaking change?" discussion.
4) A super long list of "breaking changes" in the blog posts gives the appearance of unstable software to new users who might be considering Home Assistant.
5) Similar to above, existing users are much more likely to skip releases if they see a huge list of breaking changes.

Personally, I don't believe it would lead to a huge influx of new beta testers either. The reality is that most people simply don't want to beta test crucial software that their entire smart home relies upon, especially if everything is currently working fine for them. Maybe you attract people that were on the fence before to try the betas, but I don't think it would make a big difference.

I think there are other more valid reasons for going to a monthly cycle, such as lessening the workload for Paulus and Pascal, but some of the suggestions above that it somehow improves the breaking changes user experience feel extremely inaccurate to me. Yes, users would only have to deal with breaking changes half of the time, but **each individual update will be way more stressful** for them, and that is not a good thing.

**Comment by amelchio** [comment] 2019-05-04 06:15
@balloob @pvizeli Since the issue is your workload, are you interested in having other people do the releases (cutting branches, writing release notes, managing bugfixes)?

(just repeating what @rohankapoorcom said)

**Comment by balloob** [comment] 2019-05-08 04:45
Sorry for not responding, guess the notification got dismissed or something.

Yeah, I would love help with that. Most if it is automated, but when automation fails, it gets hairy. Things that still need manual work:
 - when running milestone cherry picking script, if a PR doesn't apply cleanly
 - when release notes generated, running a 404 finder extension to mark all broken links (which usually means we missed a PR). There is also `hassrelease unmerged_docs`, which scans merged PRs for doc PRs that are not merged.
 - breaking changes formatting (has been done by Cogneato last few releases)
 - Writing the actual introduction to the release note. Figure out what we actually merged, find videos/screenshots with cool examples and putting it all together. I now usually do this the day off the release, but it can be done as soon as we cut beta and it would probably be more informative.

**Comment by amelchio** [comment] 2019-05-29 16:07
So we could fix the workload problem by only doing releases when a release manager has volunteered :)

I for one am definitely willing to handle the hairy stuff for a single release every now and then. Am I alone? Preferably, non-developers should volunteer for the last three bullets but I could guide about Git stuff, working with scripts, etc.

**Comment by frenck** [comment] 2021-01-26 00:23
This architectural issue is rather old. We now have a monthly cycle. For more information check the closing keynote of the Home Assistant Conference 2020 (available on YouTube).

**Closed by frenck** 2021-01-26 00:23 UTC
