### ISSUE TITLE
Allow a State's last_changed and last_updated to be set manually

### ISSUE THREAD

**Issue by unibeck** [home-assistant/architecture#190] opened 2019-04-08 00:59 UTC
I have completed the work for my solution to this problem and created a [PR](https://github.com/home-assistant/home-assistant/pull/22872), but as @awarecan mentioned, this change warrants discussion here first.

I propose we allow a state's `last_changed` and `last_updated` datetime values to be manually set by components. This is helpful for asynchronous data that is not guaranteed to be processed by Home Assistant immediately or in order. This is preventing me from collecting reliable data from clients because of slow processing and high latency. This will also help those who would like to integrate [daily reporting](https://www.reddit.com/r/homeassistant/comments/8vfkyx/set_state_with_historical_data/). 

The first pass of such a change is easy to implement into the current State's framework without any regressions. My PR can be a prototype for how this can be done without tearing apart the State's framework. I am open to other ideas as well -- perhaps this would fit better as an event? Though adding two boolean values into the State's framework, as my PR does, to enable such a powerful feature seems like a no brainer.

Lastly, I believe we should also implement at least one component to take advantage of this feature in its first pass. The template sensor is a great candidate because it's a flexible component and can be used by users until more components implement this feature.

Thoughts?

P.S. seems like #155 might benefit from this.

**Comment by awarecan** [comment] 2019-04-08 02:42
Add two fields in the state machine is a big change in my opinion. 

I think `last_update` should always reflect its name, e.g. when the state updated.
However, `last_changed` should be allow to manipulate, by add `last_changed` argument in `set` and `aync_set` method

```diff
    def async_set(self, entity_id: str, new_state: Any,
                  attributes: Optional[Dict] = None,
                  force_update: bool = False,
+                 last_changed: Optional[datetime.datetime] = None,
                  context: Optional[Context] = None) -> None:
``` 

Then we can add a property field `last_changed` in Entity class, default implementation should be always return `True`. Integration could override it to provide specific `last_changed` time then pass it into `State.async_set` in `_async_write_ha_state` method.  

```diff
        self.hass.states.async_set(
-           self.entity_id, state, attr, self.force_update, self._context)
+           self.entity_id, state, attr, self.force_update, self.last_changed, self._context)
```

**Comment by awarecan** [comment] 2019-04-08 02:47
I have a potential use case for my Solar panel which "current" reading actually is several minutes ago's data by design.

**Comment by dgomes** [comment] 2019-04-08 08:14
There are various smart meters who have an API that publish the time the meter was last updated. This PR would be useful for those. (It's always difficult to figure out if it's the meters fault or the integration fault that the sensor has not been updated in a while...)

**Comment by unibeck** [comment] 2019-04-08 12:55
> Add two fields in the state machine is a big change in my opinion.

Yes, I agree. And looking back into my PR I do not think they are really needed either. I would using the booleans as a way to determine if the state's datetimes were manually changed. But why should that matter? The only place I used the booleans was in the influxdb component, but even there they are not needed.

I also agree that `last_changed` and `last_updated` should stay true to what there names are. I don't think what I proposed or what my PR implements strays from that at all. Providing both of these datetimes are about making sure the state's `last_changed` and `last_updated` are true to when the state changed _or_ updated in real life. This means that both of these values will be in the past. It does not matter that a state has occurred in the past, they still need the same ability to appropriately set both `last_changed` and `last_updated`.

As for the example code you provided and your recommendation, that's exactly what I did in my PR (though your variable names are different).

@awarecan and @dgomes, I'm glad you guys already see the value in something like this. I think this is a huge step forward for HA to track state changes asynchronously.

**Comment by unibeck** [comment] 2019-04-08 13:00
It seems like we are very close to agreeing on the appropriate changes. I think the only thing we need to work out is if components should be able to set `last_updated`. I think we do given my second paragraph in my previous comment.

**Comment by michaelarnauts** [comment] 2019-04-08 15:24
It might be worth mentioning this on the docs that automations can therefore trigger with old data (that's freshly published nevertheless).

**Comment by unibeck** [comment] 2019-04-10 23:06
Is there anything needed from me to drive this forward? I would like to get this feature, whether it's my current PR or not, into HA sooner rather than later

**Comment by balloob** [comment] 2019-04-14 04:33
We should not add this feature. It is going to over complicate an already very complex system. Any state_changed event will now need to be checked, because it could be in the past. And then each place will need to define how old is _too old_ to care about it etc etc. 

It is not worth it. We can't solve every case, and if we do, our system becomes unusable. Hard no.

**Comment by unibeck** [comment] 2019-04-14 19:57
I understand Paulus. How about we tackle this from a different angle to address some of your concerns:

>Any state_changed event will now need to be checked...

Perhaps we create a new event that only publishes old states. That is, the old state event will only be fired if the current state's `last_changed` is greater than the new state's `last_changed` value. That way there is no need to check if the `state_change` event is in the past. Automations and components will still work as they currently do.

>our system becomes unusable

With a separate event, implementing this feature will cause no regressions and will not add much complexity. The change to the core system will be adding a conditional block:
```diff
         self._states[entity_id] = state
-        self._bus.async_fire(EVENT_STATE_CHANGED, {
-            'entity_id': entity_id,
-            'old_state': old_state,
-            'new_state': state,
-        }, EventOrigin.local, context)
+
+        if last_changed > old_state.last_changed:
+            self._bus.async_fire(EVENT_STATE_CHANGED, {
+                'entity_id': entity_id,
+                'old_state': old_state,
+                'new_state': state,
+            }, EventOrigin.local, context)
+        else:
+            self._bus.async_fire(EVENT_HISTORIC_STATE_CHANGED, {
+                'entity_id': entity_id,
+                'current_state': old_state,
+                'history_state': state,
+            }, EventOrigin.local, context)
```
The proposed event could be called `historic_state_change`, `stale_state_change`, `async_state_change`, `old_state_change`, other ideas? The recorder component will need to listen to the event so I can still save previous states to the database. All other state persistence components will need to listen to this event if they want to implement this feature. I think this is the standard approach to new feature implementation in HA anyways.

Any additional thoughts on this amended proposal?

**Comment by balloob** [comment] 2019-04-15 04:56
This won't work, because now our state_changed_event, which contains the old and new state, is now potentially no longer pointing at the correct old state. 

Even being able to add states that are not from _right now_ will change the system fundamentally, making the current system more complicated, and hindering any future feature addition.

We should not add this feature.

**Comment by dgomes** [comment] 2019-04-15 09:53
This probably doesn't address all use cases, but can we have a recorder service to store past events and route around HA core ? I think this solution would address some use-cases.

**Comment by unibeck** [comment] 2019-04-15 12:33
@balloob 
>This won't work, because now our state_changed_event, which contains the old and new state, is now potentially no longer pointing at the correct old state.

That's kinda the point. This type of stuff is async in nature where nothing is guaranteed to be in order. The intended purpose of such an event is to backfill data. If a component wants to listen to the event, they'll have to know that they cannot assume anything, it is WYSIWYG. The idea is the same for automations, and most automations won't make much sense to trigger on an event with old, not in order data. This can be noted in both user and dev documentation.

>Even being able to add states that are not from right now will change the system fundamentally, making the current system more complicated, and hindering any future feature addition.

I  am under the impression this will hardly affect the current core system as it will be optional and loosely coupled. To help me understand, could you provide an example or two of how this feature would convolute any workflow for a given component?

**Comment by balloob** [comment] 2019-04-15 17:56
I have no time for this discussion. There are 1000 other, more important, things for me right now. We are not interested in things that make the system more complex. Feel free to fire your own events in your custom components but we shouldn't add that as a core feature.

**Comment by unibeck** [comment] 2019-04-16 01:02
Could you delegate this to another person or group of people if you do not have the time? I am trying to help and add value to the project. Perhaps if we worked through this problem I would be available to help with the "1000 other, more important" issues.

I would appreciate a couple examples as to why this feature is detrimental to the project in any capacity.

**Comment by awarecan** [comment] 2019-04-16 01:49
@unibeck this issue is still open, other members of home-assistant organization may still have interest to continue the conversation. 

However, this is an open source project, most of people are using their free time to participate, and nobody have privilege to ask how others allocate their own time.

**Comment by unibeck** [comment] 2019-04-16 01:56
@awarecan I think you misunderstood my comment or perhaps I wasn't clear. I'm being respectful of everyone's time here and I understand there are other priorities for this project. That why I asked if @balloob would like to hand off the discussion to others.

**Comment by unibeck** [comment] 2019-07-02 11:26
I have created a custom component to support states that have occurred in the past. My project and more details are available at https://gitlab.com/jbeckman/retro_state.

I also wrote a blog post to that summarizes my experience and journey at https://medium.com/@jonathantbeckman/historic-states-in-home-assistant-3ffe2ae0480a.

I will leave this issue open as creating historic states _natively_ is still an active request from users and developers. As a matter of personal policy, I will not continue to contribute to this PR or Home Assistant. However, feel free to draw inspiration from my custom component as extracting a native port would be quite simple.

Thank you for everyone's time and input, it was greatly appreciated.

**Comment by pvizeli** [comment] 2019-07-04 19:13
I close this issue. Nice to see that you were able to solve your use case with a custom component.

This will not end up in an ADR, so there is no need to hold on that currently. Feel free to open a new issue and give a new try later.

Thanks for contribution

**Closed by pvizeli** 2019-07-04 19:13 UTC
