### ISSUE TITLE
Add a fan component with "n" speeds - up to 6

### ISSUE THREAD

**Issue by paulearley** [home-assistant/architecture#414] opened 2020-08-02 16:18 UTC
## Context

I have two fans one with 4 speeds and one with 6. I would like to be able to use all speeds. Multiple fans have more than 3 speeds.

## Proposal
Create either two new components (4 speed and 6 speed) or better yet, one component that allows for a variable number of speeds. I have been trying to work on this for a week (creating a custom component that interfaces with fans using mqtt or other means) but have gotten stuck on accessing mqtt from my custom component.

## Consequences

If the original component is modified for a variable number of speeds (which seems like the best solution) that component will be a bit more difficult to set up.

**Comment by Jc2k** [comment] 2020-08-02 16:25
This is really a dupe of https://github.com/home-assistant/architecture/issues/127.

The consensus there seems to be optionally allowing fans to provide a percentage control, but there isn't a final consensus/agreement yet.

**Comment by MartinHjelmare** [comment] 2020-08-03 20:34
Duplicate of #127

**Closed by MartinHjelmare** 2020-08-03 20:34 UTC
