### ISSUE TITLE
Reduce friction around discovery and persistent notifications

### ISSUE THREAD

**Issue by Jc2k** [home-assistant/architecture#250] opened 2019-06-15 09:17 UTC
I don't have a concrete proposal but as per the end of https://github.com/home-assistant/home-assistant/issues/24526 i wanted to start a discussion around this.

CC @balloob @Kane610 

Previously users could say whether or not they wanted to enable discovery for a particular class of devices by editing their configuration.yaml:

```
discovery:
  enable:
  - homekit
  ignore:
  - apple_tv
```

I think one of the main reasons for having this switch is that some integrations configure themselves automatically based on discovery? So the only way to not have that integration add itself to your setup is to block its discovery.

With config flow that is not an issue. There is an explicit opt-in to a device, you have to configure it before entities appear on your dashboard.

With that in mind, we didn't add the ability to opt out of a particular discovery with the new discovery components.

However, when a device is discovered we add a notification. If that notification is dismissed but then you restart HA the notification comes back.

Am i right in saying: the purpose of the notification is to aid users who are not familiar with the Integrations page find it?

I think there are a couple of user stories here:

1. I don't want to have a device that is technically supported in my HA setup, not now not ever.
2. I don't want to setup a device right now, but I may want to in the future.
3. I don't want to use my Ecobee with HomeKit, as i prefer the native integration.
4. There is a bug and a device is mis-discovered, and a user used to disable a discovery to work around it. (This happened recently, if i understood correctly)

In all cases the notification is quickly a source of friction.

Maybe we could keep track of devices we have discovered and made a notification about? A storage with a list of (DOMAIN, mac) or something similar.

Maybe we could only guide people to the integrations section once, and not every time new stuff is discovered.

In all cases the ability to create a "ignore" config entry (async_step_ignore) would mean that the user stopped getting the notification and was happy.

For case 2 we need to be careful to make sure the device isn't "lost" from the integrations page - it still needs to show in the list of discoveries and be easy to set up later.

For case 3, we can be better at using the HomeKit discovery mechanism to guide people to the right integration (i.e. the new homekit key in the manifest) - and this would stop HomeKit showing those devices as available. But would it be better to give users a choice of protocol (e.g. some users are interested in the HomeKit Ecobee support because it works even if the internet connection or cloud service goes away).

I wonder if we can guide users to file bugs in case 4, so that we can actually fix them.

Does anyone have any better ideas?

**Comment by balloob** [comment] 2019-06-15 19:24
I like the ignore step idea. It means that the config flow can add support for ignoring a discovery, as only a config flow can decide if a discovery has already been seen and has to be ignored.

We can add a new category, and that category might show up somewhere else on the integrations page. That way, people can see a list of "ignored" integrations and choose to rediscover them. 

For the Ecobee local vs Homekit flows. I think that we should always have discovery favor the brand integration over generic integrations like homekit controller. If a user wants to control it with HomeKit, they can start a HomeKit controller config flow, which will then do a discovery and list all devices that can be integrated, including Ecobee (if I am correct).

Right now what is happening about mis-discovery is that things like Ecobee currently do not have a config flow, and so we can't route discoveries to it.

**Comment by Jc2k** [comment] 2019-06-16 06:36
One problem with intercepting hap zeroconf records from HomeKit is that I can't handle it when `c#` changes. That value is only available over zeroconf annoyingly, and it allows the device to signal that a new accessory was added to the bridge or firmware was upgraded etc. So I think actually homekit_controller should always get to see `hap` records (rather than the current method). The choices there are:

 * We always deliver the discovery to homekit_controller. It handles it if there is a matching config flow. If there isn't a matching config flow and there is a brand integration (it would use the data collected from the manifests) it ignores it.

 * We always deliver the discovery to homekit_controller. We will have a mechanism to mute the notification so it doesn't matter if the device shows on the discovered integrations page.

 * homekit_controller launches its own zeroconf ServiceBrowser to monitor c# changes by itself

**Comment by Jc2k** [comment] 2019-06-16 06:38
BTW, I don't consider the Ecobee a mis-discovery. I think that is a valid discovery, and there will be a subset of users where it is a better choice to use a local only integration rather than an internet based one. An example of a mis-discovery is more like this one: https://github.com/home-assistant/home-assistant/pull/24442

**Comment by balloob** [comment] 2019-06-17 16:07
If you need the discoveries for `c#` changes, I'm fine with letting it also go to homekit controller. Just make sure that homekit controller aborts the flow when the discovery was forwarded to a config entry.

**Comment by Kane610** [comment] 2019-06-17 17:10
Ignore sounds great! Somewhere we would either need to be able to remove ignore and go directly to configure a config entry, or just remove ignore letting next discovery happen.

If we would allow the first one it would be nice if discovery could update entry data ignored entries just as with ordinary entries

**Comment by balloob** [comment] 2019-06-17 17:48
Updating config entries would be for config flows to decide. An ignored entry could still contain whatever data the integration wants. When the config entry remove is triggered, an integration can just trigger a new discovery step of its config flow.

**Comment by SeanPM5** [comment] 2019-06-17 18:33
Made a few mockups for how the user experience could be based on the existing proposals and a few more ideas of my own. Hope this is ok, I can delete this if not.

**Single device discovered**:

![discovery-notification-single](https://i.imgur.com/73AtKp3.jpg)
- When it's a single device the integration name, discovered device, manufacturer name would be displayed in a user-friendly way on the notification. Far more informative and less likely to be ignored by the user. I don't know how feasible this part is.
- The "Check it out" hyperlink that takes you to the integrations page was moved to an actual "Configure" button. And now when this button is pressed it would start the config flow process right from the notification for maximum convenience.
- The "Ignore" button would stop notifying the user of that specific device discovery. 
- Vertical ellipses / more actions menu on the right could contain numerous other options such as "Disable discovery notifications for this integration", "Disable all discovery notifications", "Remind me later", etc.

**Multiple devices discovered**:
![discovery-notification-multiple](https://i.imgur.com/Ox5gLa7.jpg)

When multiple devices are discovered the "configure" and "ignore" buttons are replaced with a "Go to Integrations" button instead. This is overall pretty similar to the way the existing notification works right now, except with tweaked text and design.

**Ignoring a discovery:**

If user chooses to ignore a discovery, it would display a "toast" prompt at bottom of page for a couple of seconds allowing them to quickly undo / un-ignore if they made a mistake:

![ignored-prompt](https://i.imgur.com/htumLmQ.png)

**Integrations Page**:

![discovery-tab-with-badge](https://i.imgur.com/OTC72FT.jpg)

Discovered devices would now appear on their own dedicated tab and potentially with a badge like this. The idea being that even if a user has chosen to disable discovery notifications completely, they'd still be made aware of new devices via the badge number when they visit the integrations section. Ignored discoveries would not count towards the badge number.

This "Discovered" page would show the discovered devices available to configure at the top. And underneath it would be an "Ignored" section (perhaps collapsed by default or behind a "Show Hidden" button or something). So this gives the user an opportunity to still configure something that has been ignored. 

Also on this page would be a toggle for turning on/off discovery notifications system-wide. This allows user to disable the notifications _before_ they even receive them. And if a user has disabled notifications from the vertical ellipses/more action button mentioned above, this would be how they turn them back on.

**Comment by Kane610** [comment] 2019-06-17 18:35
If we're doing this I'd also like to see "ignore all future discoveries for this integration"

**Comment by balloob** [comment] 2019-06-17 19:48
One downside with showing the configure dialog from the notifications panel is that people will not learn about the integrations page.

**Comment by SeanPM5** [comment] 2019-06-17 21:32
That's a valid concern but I think it can be easily addressed by simply adding another sentence to the notification.

"Home Assistant has detected a new Hue color lamp by Philips on your network. You can configure it now or at any time via the Integrations page."

Could also be listed in the more actions menu too. So when user clicks the 3 dots icon on the right there'd be options for "Ignore discovery for Hue", "Ignore discovery system-wide", "Go to Integrations page"

**Comment by SiliconAvatar** [comment] 2019-06-20 01:27
> For the Ecobee local vs Homekit flows. I think that we should always have discovery favor the brand integration over generic integrations like homekit controller. If a user wants to control it with HomeKit, they can start a HomeKit controller config flow, which will then do a discovery and list all devices that can be integrated, including Ecobee (if I am correct).

My $0.02 is that this isn't a great idea, and the idea of just showing everything that's available, and letting users choose to 'ignore' it if they don't want it is better.

My user example is that I had no idea that I could even use the homekit integration for EcoBee since I don't own any apple devices, until it popped up in 0.94. EcoBee's servers have been flakey so I added the Homekit one as a backup when their cloud service is down.

If HA had hidden that because I already use the brand integration, I would have never learned about a cool possibility that HA offered.

**Comment by dohlin** [comment] 2019-07-18 17:11
I'd like to add my weigh to this...the 'solution' of setting up the integration to resolve this isn't even always a valid workaround.  I posted [here](https://community.home-assistant.io/t/please-help-how-to-permanently-ignore-auto-discovered-homekit-component-notification/126991/4) about an issue I'm currently having where doing that isn't even an option.  It really bites to not be able to get rid of this stupid, entirely unnecessary notification :(

**Comment by Jc2k** [comment] 2019-08-07 13:34
Right now users get reminded they have discovered devices they don't plan on pairing with HomeAssistant and they can't turn that off. The notifications just keep coming back.

At least in the short term I wonder if the best option would be just to remove the "new discoveries" notification entirely? IIRC there is sign posting during the new users onboarding flow to lead users to the integrations page, so i dont think the UX will be affected too much.

**Comment by dasb00ter** [comment] 2019-08-11 20:29
Feel free to remove this comment if it is unneeded. I just thought I would add that although the notification causes "friction" it also too me as a basic user seems to be just wrong. I receive notifications for HomeKit Accessories yet I don't have a single apple/Mac device in my environment. I understand that you the developers can make it so I can opt to ignore it. Still it seems that I shouldn't actually receive a notification at all. I may have misunderstood the dialogue here so feel free to ignore

**Comment by Jc2k** [comment] 2019-08-11 20:53
@dasb00ter you may not have Apple hardware but you have clearly have devices that support the  HomeKit protocol. You do not need Apple hardware to use these devices via the HomeKit protocol, so it’s not wrong for HA to let you see that they are available.

**Comment by rradar** [comment] 2019-08-14 21:50
Please. I'm I long term home assistant user and didn't had any(!) annoyance with it (for sure I had hard times tho!) over the years - till now!

It's just badly annoying that I get spammed for integrations which have been discovered and I just can't ignore it! #25928

This needs to be fixed before 1.0 - please!

**Comment by ronschaeffer** [comment] 2019-08-15 13:21
Another reason to have an ignore option is that devices types which aren't actually supported are apparently discovered if they're using zeroconf. For example, my Arlo base station [received an update enabling HomeKit](https://community.home-assistant.io/t/new-homekit-accessory-basestation-reported-think-its-arlo/131729) and was discovered by HA even though the HomeKit controller integration does not support cameras.

Unfortunately, I can't work around the discovery notification by pairing the Arlo base station with HA anyway, because it does not having a pairing code.

**Comment by mjorgef** [comment] 2019-08-20 08:21
Iam on the same situation, I had already two lamps added to the home assistant, but now they don't work, because discovery found the two lamps and need the codes.

<img width="703" alt="1" src="https://user-images.githubusercontent.com/54062899/63330476-cfdeb580-c32b-11e9-8e4d-cdf7addc5d4d.png">
<img width="566" alt="2" src="https://user-images.githubusercontent.com/54062899/63330479-d1a87900-c32b-11e9-9046-d888d1c5c691.png">

**Comment by Jc2k** [comment] 2019-08-20 08:25
@mjorgef that sounds like a different situation or a misunderstanding. This issue does **not** stop integrations working, it just means you might have some *extra* integrations you don't care about using in your discoveries list. If Yeelight isn't working you should raise an issue for it, it's not caused by this.

**Comment by ctrl50** [comment] 2019-09-07 08:13
Tired of seeing the notification for home kit. PLEASE fix this nonsense.

**Comment by heymoe** [comment] 2019-09-24 15:39
It's been over 3 months and 5 home assistant versions later (0.94-0.99) since we lost the ability to disable / ignore certain hardware from being auto discovered (e.g: HomeKit) that we don't ever plan on implementing (e.g: not a Apple ecosystem user) and thus have to deal with a "new device discovered" notification that we can't dismiss forever. As in we can dismiss it but it comes back after X mins / hours.

**This basically turns the notification system into a notification system that cried wolf** in that legit notifications can / will get over looked because when we see there is a new notification we assume it's just another "new device discovered" notification again.

There hasn't been any update to this open issue for a month so I'm just checking in to see if there is any updates on coming up with a solution to this issue. 

Thanks for your time.

**Comment by hijackindie** [comment] 2019-09-28 12:30
I can only concur. I basically ignore the notifications now. I sure wish this would get looked at. I am ok with most of the proposed solutions. Please act on this. Thx.

**Comment by JranZu** [comment] 2019-09-28 20:02
We need a way to ignore everything related to Homekit - I'm not sure why the devs of that module thought they were more entitled than others - but since their code was included I have nothing but trouble with Homekit trying discoveries trying to force there way in. I don't have a single apple product in my house!

**Comment by Jc2k** [comment] 2019-09-28 21:17
Can we please keep contributions to tickets technical please. It's very rude to put words in the mouths of any of the people contributing their free time to make the software that you are using and actually couldn't be further from the truth. And it's not at all constructive!

This is a generic problem and needs a generic solution. There is no way to ignore a discovery that you don't have any plan to use, and that applies to every integration that uses one of the discovery mechanisms like zeroconf. There are a couple of solutions being suggested but no one has had the time to implement one yet.

I, one of the "entitled devs", not only started this discussion but have offered to implement one of the proposals (https://github.com/home-assistant/architecture/issues/250#issuecomment-519099333). The offer is still there.

FWIW, you *do* have devices on your network that use the Apple HomeKit protocol. That's why you have this notification. If you do have a device detected as Apple HomeKit and isn't we'd love to figure out how to hide that - but that's not this ticket, thats a bug.

This has got nothing to do with what Apple gear you have. You don't need to be an Apple ecosystem user to benefit from the homekit_controller integration. Home Assistant can connect to the accessories and pair and control them. Apple hardware or accounts are not needed in the slightest. It's just a brand name for some JSON sent over http over your local network. For some users this is a win - there are people on here that switched from talking to their thermostat via a flaky cloud API over a flaky DSL connection to using a local LAN based protocol that can still do stuff even if they unplug the internet entirely. We have a duty to support those use cases as well.

**Comment by JranZu** [comment] 2019-09-30 14:19
@Jc2k  - I apologize - I was having a very stressful time trying to get HA back up and running - not just because of this. That doesn't make it right. Thanks for explaining the causes.

**Comment by andrewatwood** [comment] 2019-10-08 11:48
Another angle here: a bit more annoying than seeing the prompts that won’t go away which is fine overall but ultimately hiding them is nice to have, my actual native HomeKit setup is destabilized for some reason when the HASS HomeKit discovery/zeroconf service is running. Something with the mDNS traffic takes my Lutron bridge offline in HomeKit, which took several hours to troubleshoot when I was getting set up, so beyond being able to ignore devices in the UI I NEED the ability to shut it off entirely or I will descend once more into madness. 

Also, Actual iOS and Mac devices are not constantly pinging for HomeKit devices to pair with, only explicitly when a user tries to add a device, so I almost question if it’s even appropriate for the HomeKit control service to function like that at all.

**Comment by Jc2k** [comment] 2019-10-08 12:44
Actually official clients do keep listening for Bonjour metadata, mDNS is not just used for pairing. It's meant to be used like this. From the spec:

> Controllers should cache the attribute database and monitor the current configuration number, c# in Table 5-7, for changes, which indicates that the controller should get the attribute database and update its cache.

Where c# as defined in Table 5-7 is part of the _hap._tcp zeroconf TXT record. We do monitor this now and update our cache accordingly.

zeroconf traffic should be harmless, if its not harmless raise a ticket against the zeroconf integration. It might be a bug in the zeroconf library we are using that we can get fixed. I think the HA policy is to fix bugs wherever possible in preference to adding workaround switches (because switches need to be discovered and turned on by each user). It would be really handy if that ticket had a pcap of mDNS traffic when the bridge was disrupted.

**Comment by estiens** [comment] 2019-12-10 05:13
This is still a problem that's incredibly confusing for new users.

Not only do I have devices already configured in HA that keep asking me to configure them again, but I have devices I paired with HomeKit that I don't ever want to pair with HA that tell me to configure them, but I can't because they have already been configured.

I also have two devices with obscure names that I don't even know what they are, but I know I don't need to add them.

Yet, I get pinged with notifications on restart and other times that I have devices. Honestly, I'd love to just turn discovery off entirely and just turn it on when I want to add new devices.

**Comment by SeanPM5** [comment] 2019-12-10 05:56
Here is something you could try as a temporary workaround. This should dismiss the notification/badge right away.

```
automation:
  - alias: "Temporary - Dismiss Discovery Notifications"
    trigger:
      - platform: event
        event_type: config_entry_discovered
    action:
      - service: persistent_notification.dismiss
        data:
          notification_id: config_entry_discovery
```

**Comment by bradsilcox** [comment] 2019-12-16 14:52
This is a horrible solution.  Why not enable Synology discovery for everyone?  Well except most people wont have something that supports it on their network.  I have done the config integration with Rachio but still see it coming up in the HomeKit discovery.  Not being able to disable this is a significant annoyance.  I will be disabling my default config to turn this off but now it puts more manual work on me.  I get that Apple fan boys like to force their integrations but this is supposed to be an open solution where as the end user we have a choice.  Whats my choice here?  Give up on default functionality of HA or deal with this annoying HomeKit notification?

SeamPM5 can your automation be updated to only dismiss HomeKit notifications?  I don't want to dismiss additional devices I may be trying to add in the future.

Thanks for listening to my rant, hope to get this resolved before I have to start disabling functionality.

Brad

**Comment by SiliconAvatar** [comment] 2019-12-16 15:08
> hope to get this resolved before I have to start disabling functionality.

This is already in progress, and has been for a while now. It's not as simple as you think to resolve.

Everyone here is aware of the issue, and the full time devs and volunteers are working on it.
You can follow the individual commits if you want to monitor the progress (one such PR linked below). Other than submitting your own PR, all you can do is wait patiently while the issue is improved. 

https://github.com/home-assistant/home-assistant/pull/29806

**Closed** 2019-12-18 06:41 UTC
