### ISSUE TITLE
Add a location configuration item to the device scanner

### ISSUE THREAD

**Issue by msmarks** [home-assistant/architecture#304] opened 2019-10-19 14:51 UTC
## Context

I have two houses that are 300 meters apart. I use a bridge to connect the networks of two houses. Home Assistant run in an computer controls all devices  distributed in two houses. I want to know if anyone is in the house and in which house person is in. But device tracker like router only tells home or not home. I can't know which house person is in.

I can install two instances of home assistant, one instance for one house. However, sometimes, it makes me tired to maintain two systems. 

## Proposal

I propose to add a location configuration item to the device scanner, like latitude, longitude.

## Consequences

When location is settled, and phone connect to the router, router device tracker use the position info to decide zone name, and return zone name as its state instead of home. When disconnect, device tracker return not home as its state.

Person components can also benefit from this change. When one person entity connects to two router device trackers in two houses, use the last zone name the device tracker report as the state of the person entity. Person entity will show if person is in house A zone, house B zone or not home.

**Comment by akloeckner** [comment] 2021-02-09 11:25
See also #463, where there is no activity, currently, either. Just thought, the link should be clear.

**Comment by balloob** [comment] 2021-04-13 05:16
Duplicate of 463

**Closed by balloob** 2021-04-13 05:16 UTC
