### ISSUE TITLE
Integration Quality/Handling for HA 1.0

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/architecture#266] opened 2019-07-28 10:37 UTC
## Context

The current situation with integration is nothing that should be for a 1.0 release. I realize after climate migration that 70% of the integrations are not maintained and maybe 10% of the integrations are broken. It's nice to say we support over 1200 interfaces, but the quality of this integrations are unknown. The frustration is high sometimes because user buys hardware and see later that it doesn't work. We have a quality scale, but no one cares about this.

An integration store like Google/Apple have for smartphones is also not the solution because it ends up in lost more quality. We can look to other big projects, and we will see that the best solution is at the end, a core and community collection of integrations.

Next big issue is that too many people have now write access to the main repository. If one of that accounts going out of control, they can do significant damage. It's also really hard to do manage that all over one issue/pr tracker. Well, labels help a bit.

## Proposal

We should split the integrations out of the main repository. Core developers maintain core integrations. They would be:

- Any platform models (light, switch, climate, ect)
- Automation
- Template
- Scripts
- Sun
- Frontend
- http
- websocket/api

We also include all Integration they are responsible by Hardware Manifactor as certificated integrations. That means the Vendor needs to be responsible for core developers and take active care of his integration. More details about certificated integrations are on ADR00X.

All other integrations are inside community collections. The release also includes the community integrations, so there are no changes for the end-users.

But if there is no maintainer and we need to believe that this will not work anymore, we move the integration into an archive repository until someone reanimate it. We should handle that like the Linux Kernel. Archived integrations are not shipped with the Release and can be used as a custom component.

## Consequences

Before Home Assistant 1.0 will be released, we have the quality of the integration more under control. The community collection follows the same release circle as Home Assistant and is embedded as sub repository. We have automation to take that together.

**Comment by frenck** [comment] 2019-07-28 10:41
> But if there is no maintainer and we need to believe that this will not work anymore, we move the integration into an archive repository until someone reanimate it.

Possible unclear: Are the archived integrations included in the releases?

**Comment by pvizeli** [comment] 2019-07-28 10:43
No, they are not included and can be used as customer component

**Comment by DubhAd** [comment] 2019-07-28 11:23
IMO if this is done (and I think separating out _maintained_ from _abandoned_ is a good idea) then it would be really good if something like [HACS](https://custom-components.github.io/hacs/) was part of HA. Then, like people can with Hass.io add-ons, people can still use them without having to struggle through setting up a custom component/integration.

It'd also make sense to tag all these things with the date or version they were last updated, and provide an easy way of allowing people to report that they don't work with a specific version.

**Comment by MartinHjelmare** [comment] 2019-07-28 11:39
How will the management of the community collections contributions work? Who will have write access? Who will do code review?

**Comment by pvizeli** [comment] 2019-07-28 12:19
@MartinHjelmare Like now, this repository work like the old main repository. The main repository will be closed to the core team only.

@DubhAd a store will be no options for now. The quality will be lost with a Store. It's fine that somethings like HACS are around and you can use it as custom components. I know that with Hass.io because 90% of the available add-ons outside of core/community are shit and horrible quality. That is nothing that we want have on HA itself.

**Comment by MartinHjelmare** [comment] 2019-07-28 12:39
Is this clarification correct?: The reason for the split of repositories is to limit the people with write access to the main repository. The reason for the archiving of unmaintained integrations is to better control the quality of the integrations.

**Comment by pvizeli** [comment] 2019-07-28 12:43
No. We split the integration into core/community because of the quality scale that the core add-ons are maintained by core/manufactory and the community by community. We also solve that we don't have 70-80 person with write access to the main repository/automation.

Unmaintained don't move only to archive if there is a reason to believe that they don't work anymore and maybe after a due like on Linux Kernel.

**Comment by MartinHjelmare** [comment] 2019-07-28 12:54
Is it correct that there currently are no hardware manufacturer certified integrations?

**Comment by pvizeli** [comment] 2019-07-28 13:32
Yes, but that is something that we want to change in the future. I work with some manufacturers and the interest are available. But how that will look like is a part of followup ADR.

How we solve the quality management on community integration is somethings that we need to learn after this ADR.

**Comment by frenck** [comment] 2019-07-28 14:11
IMHO, we should take smaller steps.

First, split the core & integrations into separate repositories. Don't tread any integration differently.

For the future, we should keep out integration out of the core. However, we could split the integrations into 3 different ones.

1. Core maintained, Certified & Platinum integrations
2. Community integrations
3. Archived

Nevertheless, I do think splitting that should be a second step / different discussion or even different ADR. Settling on a split in core & integrations part and actually doing that, would be a pill large enough to swallow for starters.

About archiving integrations, from a maintenance perspective, yes I understand, from a user perspective: That is one freaking breaking change that will make users very unhappy if it happens.

**Comment by pvizeli** [comment] 2019-07-28 14:29
> Unmaintained integrations move to archive if there is a reason to believe that they don't work anymore and maybe after a due like on Linux Kernel. But that can be specified in a follow ADR.

Other I agree. But core integration should be in core like now - > template, automation or models like light, switch

**Comment by Jc2k** [comment] 2019-07-28 16:05
Is the TL;DR that on its own this ADR would just create a split between core and community and following that the implication would be that it’s not HAs fault if you use community integrations and they break? So it’s about managing expectations of users because core HA can’t realistically be maintaining low quality integrations where the original author has left.

And I guess it’s fair to say this ADR explicitly doesn’t and can’t improve our users experience because an ADR can’t cause there to be more maintainers all of a sudden. So all we can do is manage expectations.
 
So this is something like how Ubuntu has a universe repo. The software is accessible but may not be supported by anyone at all.

Isn’t the real challenge surfacing the quality level and support level to the users, ideally on the website and in the admin panel. Rather than starting with a repo split could I propose a field in the JSON metadata that says if it’s core, certified, community or unmaintained. This could be mirrored in the docs and maybe the admin panel could show the active integrations and their support level too.

Core and certified are fairly self explanatory. Community means there are listed and active CODEOWNERS. For now unmaintained means no codeowner.

I think the existing tier system has a lot of merit and we could develop it further. Maybe we shouldn’t ship unranked integrations. Maybe achieving getting top status should be like a community version of getting certified.

**Comment by Adminiuga** [comment] 2019-07-28 17:06
IMO we should allow users to "opt-in" into sending integrations usage statistics, so just we have a better understanding which ones could be archived.

**Comment by Jc2k** [comment] 2019-07-28 17:23
Re stats - in a situation where an integration is broken, there is no CODEOWNER and no one on the core team has a device to test with (and/or are just busy with core stuff), is there even a popularity level high enough that would mean the core team could/would take over? I wouldn't of thought there could be really?

**Comment by fabaff** [comment] 2019-07-28 18:45
> IMO we should allow users to "opt-in" into sending integrations usage statistics, so just we have a better understanding which ones could be archived.

@Adminiuga, see https://www.home-assistant.io/components/updater/

**Comment by Adminiuga** [comment] 2019-07-28 20:17
> see https://www.home-assistant.io/components/updater/

HRM, I did not realize this is already there. Last time I've asked I was told we're not collecting integration usage statistics. This makes it even easier, just a checkbox in UI for an easy "opt-in"

**Comment by andrewsayre** [comment] 2019-07-28 21:06
I'm struggling to see how the proposal matches the problem statement.  Bottom line, how does separating repositories improve the quality?  The desired outcome isn't supported by the proposed changes.  What would be different that would address quality? (and why that can't be achieved now?)  I agree with @frenck about starting smaller and more focused and @Jc2k that the current quality system can be made stronger to improve quality.

The consequences section is also lacking articulation of the actual impact this would have (it's just a summary of the desired outcome).  Some consequences I see:
- Less participation in maintaining the core of HA - there are only 4 [core devs](https://github.com/orgs/home-assistant/teams/core).  We just achieved home-assistant/home-assistant#25155 (area support) with largely non-core devs, which wouldn't have happened under this proposal.  Additionally, with less people working on core, it will become more insulated from gathering community input before making decisions.
- There will be a significant impact to user experience and community devs with this change.
- It will take significant work and difficulty to determine which integrations should be archived and move/separate the code base into the new target repos.
- It seems to value vendor maintained integrations over community maintained.

**Specific comments/suggestions:**

> We also include all Integration they are responsible by Hardware Manifactor as certificated integrations. That means the Vendor needs to be responsible for core developers and take active care of his integration

Vendor maintained integrations aren't going to be of higher quality just because it's got company devs working on it.  Why would we grant certified status and include them in the main repo?  There should be objective criteria for any integration to be certified, whether vendor maintained or not.

> Next big issue is that too many people have now write access to the main repository. If one of that accounts going out of control, they can do significant damage. It's also really hard to do manage that all over one issue/pr tracker. Well, labels help a bit.

This is unrelated to quality and frankly sounds more like a fear tactic to garner support the proposal.  Can examples be provided that show this to be a problem?  Instead, I'd suggest implementing guidelines for # of contributions required on a monthly/quarterly basis to maintain membership.  GitHub already tracks this information and would be easy to monitor and enforce...  But again, this will not improve quality.

> But if there is no maintainer and we need to believe that this will not work anymore, we move the integration into an archive repository until someone reanimate it.

I agree with archiving and this can be setup by making minor changes to the current quality scale today.

**Comment by cgarwood** [comment] 2019-07-29 13:33
I agree with everything @andrewsayre mentioned above.

I also agree with @DubhAd that something like HACS would be a great addition. I'm only using 20 or so integrations in my setup, I don't _need_ the other 1180 integrations sitting around in my system. Something like HACS makes it easy to install and update components outside of core releases, and I think that's the best way forward if we want to split integrations from the core.

A "store" also doesn't have to be "open" - HACS by default includes repositories under 1 github organization, so there is some quality control, similar IMO to how most *nix package managers include a few default repositories. If you're concerned about quality, only include the main "Home Assistant Integrations" repository that's under the HA org, and then you still maintain the quality control by having it all under the org's umbrella and oversight. Then if you want to, allow people to include custom repositories with the caveat/warning that custom repositories haven't been verified and could cause problems.

Like @Adminiuga I would be very interested in the integration usage stats. I have a feeling there's a lot of integrations with minimal users and nobody really taking ownership to support them.

**Comment by Adminiuga** [comment] 2019-07-29 19:19
>Less participation in maintaining the core of HA - there are only 4 core devs. We just achieved home-assistant/home-assistant#25155 (area support) with largely non-core devs, which wouldn't have happened under this proposal.

IMO lacking write access to core repo, still doesn't not stop you from submitting PRs

> Additionally, with less people working on core, it will become more insulated from gathering community input before making decisions.

There is a risk of this, I agree.

I agree with @andrewsayre points and while the proposed change does not improve quality directly I think it is one of the step we'll have to make anyway. in other words, what @frenck  said ;)

**Comment by pvizeli** [comment] 2019-07-30 09:47
Hmm, I think we drift a bit away from what that is. We need split integration out of core for management, not for the user. For the users, it has no effect.

The main Repository is like an overkill they try to handle everything and every issue on the same place. I never look to the issue because that did not work anymore for what it should be.

After we split out and move things into the new repository they are able to track issues. We can work on quality as future ADR.

**Comment by Jc2k** [comment] 2019-07-30 10:07
If quality is for a future ADR, does this ADR need a different title?

**Comment by JeffLIrion** [comment] 2019-07-30 13:11
Would the continuous integration tests for the two repos be intertwined?

I'm thinking about changes that have affected all the integrations, such as the introduction of the manifest.json file or moving constants around. I posted an idea in the [Decouple integration releases from core](https://github.com/home-assistant/architecture/issues/202#issuecomment-504760355) issue:

> Both repos would include the other in their CI tests. Changes to the core would test using the latest release of the integrations repo, and changes to the integration repo would test using the head of the core repo.
>
> If a change in the core requires changes in the integration repo, that developer will have to make the necessary changes to the integration repo, and the integrations would have a special release that keeps them compatible with the core. Users will not be able to update their integrations to this release or later until they update their HA core.

**Comment by MartinHjelmare** [comment] 2019-07-30 14:10
There are less drastic measures than splitting the backend into two repos, that would improve issue handling for the core. Eg making a github project board that sorts issues with core label.

There are currently only 36 open issues with core label.

**Comment by andrewsayre** [comment] 2019-07-30 14:33
> There are less drastic measures than splitting the backend into two repos, that would improve issue handling for the core. Eg making a github project board that sorts issues with core label.

I fully agree.  Let's be really crisp on what the problem is we need to solve (and back that with data/evidence) and have an open discussion about solutions.  The proposal still talks about quality and jumps right into a drastic solution that is unrelated.

**Comment by andrewsayre** [comment] 2019-07-30 14:44
> Hmm, I think we drift a bit away from what that is. We need split integration out of core for management, not for the user. For the users, it has no effect.

I think we're reacting to what was written in the proposal.  If your intent was to solve a manageability problem, can you update the issue to talk about that and how it would be improved by the proposal? (and why other measures aren't going to work?)

The development community is a major segment of _users_ and is certainly affected by this proposal.  IMO, it's the biggest asset of this project and any change that affects them should be thoroughly understood and evaluated.

**Comment by pvizeli** [comment] 2019-07-30 14:46
Everyone want to change the handling and there are a lot of different ideas around but all ideas have the minimum requirements to split integration out. As core developer I can say, all is not possible and make also not a lot of sense. But the first step is to move administrative parts out of the core repository.

**Comment by DubhAd** [comment] 2019-07-30 19:28
> > IMO we should allow users to "opt-in" into sending integrations usage statistics, so just we have a better understanding which ones could be archived.
> 
> @Adminiuga, see https://www.home-assistant.io/components/updater/

Only one problem, some time back it was publicly made very clear that the information there went to a whole two people, and no developers would get access to that information. A lot of us disabled that (opt in) component as it wasn't serving the purpose the docs claimed.

**Comment by ties** [comment] 2019-07-30 20:24
> Only one problem, some time back it was publicly made very clear that the information there went to a whole two people, and no developers would get access to that information. A lot of us disabled that (opt in) component as it wasn't serving the purpose the docs claimed.

Where was this made public?

I support the choice of never making raw information public. However if it's not available in aggregate form, it prevents this (essential) information being used for product decisions, even though it seems to be available. Getting the updater active on many installations (opt-in) and gathering telemetry, including used components, would be a major win when discussing product choices.

(I would be willing to contribute processing code in R that (a) open sources the processing applied and (b) applies [statistical disclosure control anonymization methods](https://sdcpractice.readthedocs.io/en/latest/anon_methods.html) to effectively anonymize the data, when I have time in september)

**Comment by DubhAd** [comment] 2019-08-04 17:52
> Where was this made public?

In one of the developer discord chats. Apparently even aggregate information wouldn't be made public because it would lead to incorrect things being inferred 🤷‍♂

**Comment by andrewsayre** [comment] 2019-08-07 14:23
I think this proposal has largely failed to garner support and as such am closing it.  @pvizeli I'm more than happy to work with you on what you see the problems/needs are and articulate that in a new issue so the community can understand and get behind the direction.  Ping me on Discord to chat further.

**Closed by andrewsayre** 2019-08-07 14:23 UTC
